version: "3.7"

services:
    database_oficina:
        image: postgres
        container_name: database_oficina
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=oficina
            - POSTGRES_DB=oficina
        volumes:
            - pgdata:/data/postgres
    app:
        build: .
        container_name: oficina
        restart: always
        ports:
            - 3333:3333
        volumes:
            - .:/usr/app
        links:
            - database_oficina
        depends_on:
            - database_oficina

volumes:
    pgdata:
        driver: local